service: pijon

package:
  exclude:
    - bucket/**
    - src/**
    - README.md

provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, "dev"}
  runtime: nodejs10.x
  memorySize: 128
  timeout: 15
  environment: ${file(./env/sls.env.json):${opt:stage,"dev"}}

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-domain-manager

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket

custom:
  s3:
    port: 6071
    directory: ./bucket
  stages:
    dev:
      domain: pijon-dev.becode.xyz
      domainEnabled: true
    production:
      domain: pijon.becode.xyz
      domainEnabled: true
  customDomain:
    domainName: ${self:custom.stages.${self:provider.stage}.domain}
    certificateName: "*.becode.xyz"
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.stages.${self:provider.stage}.domainEnabled}

functions:
  upload-handler:
    handler: bin/pijon.handler
    events:
      - http: POST /
  s3-hook:
    handler: bin/s3.handler
    events:
      - s3: local-bucket
        event: s3:*
